package com.coffee.server;

import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;

public class DummyData {
        public static List<Item> items = new ArrayList<>(Arrays.asList(
                        new Item(1, "Hair Bender",
                                        "The sweet and balanced coffee that started it all. Hair Bender is our most celebrated blend with a flavor profile that shines no matter how you brew it.",
                                        16,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/STCShopifyHairbender_ProductImageTransparentPNG_large.png?v=1622754826&auto=format,compress&w=540"),
                        new Item(2, "House Blend",
                                        "Our House Blend bag has officially been retired and replaced with Homestead! House Blend and Homestead are favs around here — in part because they’re so exceptionally similar — blended from many of the same components.",
                                        16,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/STCShopifyHouseBlend_ProductImageTransparentPNG.png?v=1622144063&auto=format,compress&w=750"),
                        new Item(3, "French Roast",
                                        "This toasty, organic blend redefines what a classic dark roast can be. It’s big and smoky, but never burnt.",
                                        17,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/STCShopifyFrenchRoast_ProductImageTransparentPNG_large.png?v=1622143647&auto=format,compress"),
                        new Item(4, "Roaster's Pick",
                                        "Like changing things up? Get a different coffee every two weeks—hand selected by the fine folks who source, cup, and roast our coffees—including some exclusive coffees only available through Roaster's Pick.",
                                        23,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/Roaster_sPickbadgeMordecofe_large.png?v=1679511247&auto=format,compress&w=540"),
                        new Item(5, "Blend Shuffle",
                                        "Keep it simple and fresh with a rotation of our iconic blends. We’ll send a new selection every two weeks, so you can say bye-bye to wasting away in the coffee aisle of your local grocery.",
                                        17,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/Blend_Shuffle_Holler_large.png?v=1679511223&auto=format,compress&w=540"),
                        new Item(6, "Holler Mountain",
                                        "This organic blend has been a hometown favorite since day one. It’s got the complexity to pour a great espresso yet the versatility to serve as your daily cup of drip.",
                                        17,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/STCShopifyHollerMountain_ProductImageTransparentPNG_large.png?v=1622754924&auto=format,compress&w=540"),
                        new Item(7, "Ecuador Rancho Carmen",
                                        "Stumptown sources this exquisite single origin offering from a group of 35 producers in Ecuador’s southernmost province.",
                                        23,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/SO_Bag_RanchoCarmen2023_1_large.png?v=1680551397&auto=format,compress&w=540"),
                        new Item(8, "Founder's Blend",
                                        "A smooth, all-day drinker, Founder's Blend combines certified organic coffees from Central and South America for a taste of sunshine in a cup.",
                                        17,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/Founders_Blend_Product_1_large.png?v=1649951363&auto=format,compress&w=540"),
                        new Item(9, "Trapper Creek Decaf",
                                        "Finally, decaf coffee beans that hold their own. Using the Swiss Water Process to decaffeinate carefully sourced coffees, we achieve unparalleled flavor and cup quality.",
                                        17,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/STCShopifyTrapperCreek_ProductImageTransparentPNG_large.png?v=1622755412&auto=format,compress&w=540"),
                        new Item(10, "Costa Rica Montes De Oro",
                                        "Montes de Oro is a farm and micro-mill managed by our longtime partners Emilio and Laura Gamboa in Tarrazú, Costa Rica. Their dedication to producing the finest coffee possible shines through in every cup.",
                                        23,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/STC-Shopify-Costa-Rica-Montes-De-Oro2021_Product-Image-Transparent-PNG_large.png?v=1637625830&auto=format,compress&w=540"),
                        new Item(11, "Rwanda Huye Mountain",
                                        "David Rubanzangabo operates the Huye Mountain washing station with an emphasis on community, and a strong dedication to the farmers it serves, resulting in a bright coffee with a fine, balanced acidity.",
                                        23,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/Rwanda_Huye_Mountain_2023_1_large.png?v=1673052779&auto=format,compress&w=540"),
                        new Item(12, "Peru Churupampa",
                                        "The Tocto family operates Finca Churupampa with an unwavering commitment to organic coffee production and their community.",
                                        23,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/STC-Shopify-PDP-Peru_Churupampa_1_large.png?v=1641783924&auto=format,compress&w=540"),
                        new Item(13, "Indonesia Bies Penantan",
                                        "This rich, full-bodied coffee is the result of carefully selected lots prepared and produced by our longtime partners at the women-led Ketiara Cooperative in Aceh, on the island of Sumatra.",
                                        21,
                                        "stumptown",
                                        "https://stumptown-shop.imgix.net/products/2022STC-Shopify-Indonesia-Bies_Product-Image-Transparent-PNG__2_large.png?v=1677883288&auto=format,compress&w=540"),
                        new Item(14, "Brooklyn",
                                        "A perennial filter classic, we use the Brooklyn blend as our go-to coffee of the day. Brimming with flavors of creamy cocoa, sweet toffee and rich dried fruits, this offering brews beautifully on the French Press at home and is equally tasty with or without milk.",
                                        16, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/2020_10_28_Partners_Brooklyn_shot01_3000x3000_93c02064-deeb-4d57-9ae9-944c887357bf_1080x.jpg?v=1628787927"),
                        new Item(15, "Jumpstart",
                                        "The newest addition to our mainstay lineup, Jumpstart is a versatile blend of Latin American coffees with a rich, decadent flavor profile. Jumpstart is full-bodied, with caramel sweetness and notes of Jordan almond and poached pear.",
                                        15, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/2020_10_28_Partners_Jumpstart_shot1_3000x3000_b1a89185-7132-4bff-b7d0-f600a57fc133_1080x.jpg?v=1618251951"),
                        new Item(16, "Manhattan",
                                        "Our most developed, deepest roast, the Manhattan Blend is full-bodied and rich, with dark chocolate notes, marzipan and the syrupy sweetness of molasses.",
                                        (int) 17.25, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/2020_10_28_Partners_Manhattan_shot1_3000x3000_40d15569-349f-4f59-afbb-12962aff8868_1080x.jpg?v=1618251981"),
                        new Item(17, "Colombia - El Ramo",
                                        "El Ramo is a project that showcases the impeccable flavor profile of Colombian coffees. El Ramo, meaning the bouquet in Spanish, is comprised of seasonally rotating lots from some of our closest and most favorite producers in the region. The result is a beautiful offering that is blended to maintain an exceptionally sweet and approachable profile all year round.",
                                        18, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/2020_10_28_Partners_ElRamo_shot01_3000x3000_a259825a-32ab-43af-a026-e54a2e88cc05_1080x.jpg?v=1618252046"),
                        new Item(18, "Flatiron",
                                        "Just like its architectural namesake, this espresso is a true New York classic. We crafted this blend specifically for NYC's go-getters. Expect flavors of dark chocolate, praline, and dates to shine through in your favorite espresso drink.",
                                        16, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/2020_10_28_Partners_Flatiron_shot01_3000x3000_cb2aaf86-1ba2-4b7d-a9ed-0c1f195e6ec3_1080x.jpg?v=1618251940"),
                        new Item(19, "Bedford",
                                        "Our flagship espresso at our original Williamsburg shop and roastery. Bedford is comprised of two of our oldest sourcing relationships, the coffees from which merge together to create an incredibly delicious and complex experience. Look for ripe stone fruits, citrus brightness, and a beautifully syrupy body. Amazing on its own as an espresso or try in a cortado.",
                                        (int) 19.5, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/2020_10_28_Partners_Bedford_shot01_3000x3000_20c2c839-15cb-44a4-b8eb-d2c912b31da1_1080x.jpg?v=1618251877"),
                        new Item(20, "Elevate",
                                        "A new espresso project comprised of a rotating single country focus from Central and South America. Elevate is complex with a sweet acidity and velvety mouth-feel. Crisp apples and caramel sweetness make for the perfect pairing with milk.",
                                        17, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/2020_10_28_Partners_Elevate_shot1_3000x3000_c54398c7-287b-480c-9fb0-7e3e4880ae55_1080x.jpg?v=1618252020"),
                        new Item(21, "Burundi - Gahahe",
                                        "Every single year we're impressed by Burundian coffees. This is our fourth year buying coffee from Gahahe, a washing station in the heart of Kayanza that serves over 1,700 smallholder farmers. This lot is an excellent rendering of the flavors we've come to love. Look for a warm and complex cup with immaculate clarity and layered sweetness—we taste cranberry, golden raisin, dried fig, honey, brown sugar, orange peel, and lovely, subtle florals.",
                                        (int) 17.5, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/12ozBag-Front-Gahahe-square_1_1080x.jpg?v=1677075566"),
                        new Item(22, "Brazil - Santa Lúcia",
                                        "Santa Lúcia is another lovely farm belonging to the Pereira family, our long-running relationship in Carmo de Minas, Brazil. We have partnered with CarmoCoffees for nearly all of our sourcing in Brazil from core blend components to smaller seasonal lots like this. This coffee (returning to our menu for its second year!) is delightful—expect lower acidity and heavier body in a sweet, comforting cup. We taste cocoa and hazelnut, brown sugar, apricot, date, milk chocolate, and peanut butter.",
                                        (int) 16.5, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/12ozBag-Front-santalucia-square_1080x.jpg?v=1680118968"),
                        new Item(23, "Honduras - San Francisco",
                                        "Finca San Francisco is one of several small farms owned by Roger Dominguez of Marcala, Honduras. In the last five years we've been consistently impressed with Roger, his coffees, and his passion for bettering his community through specialty coffee production. Natural process coffees can be tricky to pull off year after year, but Roger is adept. In the cup you'll find exciting red fruits like strawberry and raspberry alongside pleasantly familiar flavors of dark chocolate and baking spice.",
                                        22, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/12ozBagMock-SanFrancisco-Face-sq_1080x.jpg?v=1643032419"),
                        new Item(24, "Ghost Town - Decaf",
                                        "Decaffeinated using mountain water to create a naturally sweet and round coffee, beginning with a subtle malt flavor, enhanced with a creamy body and rich notes of white chocolate and ending with a soft acidity and golden raisin on the finish.",
                                        18, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/2020_10_28_Partners_GhostTown_shot1_3000x3000_d3e4d17c-1aaf-45d2-a80c-66507e52216d_1080x.jpg?v=1615559808"),
                        new Item(25, "Roaster's Choice Subscription",
                                        "Let us take you on a coffee journey around the globe and experience our favorite coffees of the moment. Each shipment, you will receive a new single-origin or blend selected by a member of the Partners team. Become immersed in the world of coffee as you discover new flavors from the diverse coffee-growing regions of South America, to the distinctive offerings of East Africa.",
                                        (int) 17.5, "partners",
                                        "https://cdn.shopify.com/s/files/1/0087/2074/4527/products/12ozBagMock-RoastersChoiceShuffle-Facesq_1080x.jpg?v=1605909246"),
                        new Item(26, "UTEUZI JIMBO | KENYA • WASHED",
                                        "Uteuzi Jimbo is Swahili for 'county select' and is a Regional Select program designed to highlight the different coffee-growing counties of Kenya in which Cafe Imports primarily works: Nyeri, Embu, Muranga, and Kirinyaga. These coffees are traceable down to the region, and are created by blending lots from different factories in each area, basis the cup quality and profile.",
                                        25, "whitenoise",
                                        "https://cdn.shopify.com/s/files/1/0654/4588/8257/products/Uteuzi_1x1a.jpg?v=1669996626"),
                        new Item(27, "WAYKAN | GUATEMALA • WASHED",
                                        "Our Waykan offerings are chosen for their pristine example of the dynamic character of coffees from Huehuetenango, with their crisp acidity reminiscent of lemon, grape, or apple, and a balance of toffee and sweet nuts, like almond. In the Maya Q’qnjobal dialect in the region, “waykan” means “star, or light that shines in the sky at night.” The indigenous population in and around Huehuetenango plays a large role in the coffee production here, and coffee accounts either directly or indirectly for roughly 80 percent of the local economy.",
                                        23, "whitenoise",
                                        "https://cdn.shopify.com/s/files/1/0654/4588/8257/products/Waykan_1x1a.jpg?v=1669996665"),
                        new Item(28, "MR. NARE WARE | ETHIOPIA • NATURAL",
                                        "The Sidama region is known for producing the most coffee at the highest grades in Ethiopia, and the geography explains why this is. This region spreads across fertile highlands, where half of the land is cultivated. The surrounding rivers and lakes along with the very high elevation results in cool weather and fertile soil. These factors, in combination with over 100 inches of rainfall per year, cause the coffee to ripen slower than in any other region in Ethiopia. There are over 50 cooperatives and 200 washing stations throughout Sidama.",
                                        23, "whitenoise",
                                        "https://cdn.shopify.com/s/files/1/0654/4588/8257/products/Nare_1x1a.jpg?v=1669996489"),
                        new Item(29, "SAN ANTONIO | NICARAGUA • WASHED",
                                        "PRODECOOP is a second-level cooperative organization that groups 38 grassroots cooperatives made up of 2,300 small producers, 27% of whom are women. These producers and their respective cooperatives are located in the departments of Esteli, Madriz, and Nueva Segovia, in northern Nicaragua. On average, they export 30,000 coffee bags, of which 50% of the total volume is organic and Fair Trade certified.",
                                        23, "whitenoise",
                                        "https://cdn.shopify.com/s/files/1/0654/4588/8257/products/San-Antonio_1x1a.jpg?v=1669996582"),
                        new Item(30, "LA FORTALEZA MICROLOT | ECUADOR • WASHED",
                                        "Microlots from Ecuador are sourced from independent specialty-coffee farmers and represent the highest quality and the highest level of traceability available.",
                                        23, "whitenoise",
                                        "https://cdn.shopify.com/s/files/1/0654/4588/8257/products/La-Fortaleza_1x1a.jpg?v=1669992795"),
                        new Item(31, "DANSE MORMORA | ETHIOPIA • WASHED",
                                        "Danse Mormora is located about 5 kilometers from the town of Haro Lebetu, and the farmers grow coffee in fertile clay soil at high elevation. The variety most commonly called 'Bourbon' here is not the same as that type that is better-known in Central and South America: Coffees called 'Bourbon' colloquially in Ethiopia are typical coffee-berry-disease-resistant cultivars.",
                                        23, "whitenoise",
                                        "https://cdn.shopify.com/s/files/1/0654/4588/8257/products/Danse_1x1a.jpg?v=1669992668"),
                        new Item(32, "BURUNDI TURASHOBORA",
                                        "Complex and creamy, the quality of this coffee begets the equality of the women who grow it. Experience mind-blowing floral aromatics with notes of tart pomegranate and refined malt.",
                                        22, "peets",
                                        "https://peets-shop.imgix.net/products/23DTC-4-April-LTO-Burundi-PDP-Bag-1266x1492.png?v=1679687253&auto=format,compress&w=900"),
                        new Item(33, "SULAWESI-KALOSI",
                                        "Taste heaven in your cup. A rare coffee, semi-aged and cultivated in the traditional Sulawesi method.",
                                        20, "peets",
                                        "https://peets-shop.imgix.net/products/SLW-M_1.png?v=1592873625&auto=format,compress&w=900"),
                        new Item(34, "ARABIAN MOCHA SANANI",
                                        "For those who embrace a bit of wildness, a full-bodied desert miracle from Yemen’s harsh, dry mountain terrain.",
                                        28, "peets",
                                        "https://peets-shop.imgix.net/products/ARB-M_1.png?v=1592867036&auto=format,compress&w=900"),
                        new Item(35, "JR RESERVE BLEND",
                                        "From perhaps the most discerning palate in the specialty coffee world comes this transcendent blend of exceptional, rare, full-bodied coffees.",
                                        28, "peets",
                                        "https://peets-shop.imgix.net/products/JRB8-M_1.png?v=1597695834&auto=format,compress&w=900"),
                        new Item(36, "COLOMBIA",
                                        "For those seeking exceptional, full-bodied Colombian coffee, shining and sweet from the rarest lots.",
                                        18, "peets",
                                        "https://peets-shop.imgix.net/products/COL-M_1.png?v=1592868442&auto=format,compress&w=900"),
                        new Item(37, "YOSEMITE DOS SIERRAS ORGANIC",
                                        "Feel the connection to the canopied mountains where this sustainable, Bird Friendly certified Colombian coffee is grown. Complex and satisfying with milk chocolate sweetness.",
                                        21, "peets",
                                        "https://peets-shop.imgix.net/products/YOS-M_1.png?v=1612372002&auto=format,compress&w=900"),
                        new Item(38, "BIG BANG", "Our most loved medium roast—smooth with a balanced richness.", 19,
                                        "peets",
                                        "https://peets-shop.imgix.net/products/BBC-M_1.png?v=1592867315&auto=format,compress&w=900"),
                        new Item(39, "LAS HERMANAS",
                                        "100% women-produced, Fair Trade certified, and roasted to perfection in a medium style. The cup delivers milk chocolate sweetness and satisfying, creamy texture.",
                                        20, "peets",
                                        "https://peets-shop.imgix.net/products/PDP_LasHermanas-1266x1492.png?v=1614825114&auto=format,compress&w=900"),
                        new Item(40, "ORGANIC ALAMEDA MORNING BLEND",
                                        "A medium roast organic blend that’s the perfect way to start your day; lively and caramel-sweet with floral aromatics.",
                                        21, "peets",
                                        "https://peets-shop.imgix.net/products/OrganicAlamedaMorningBlend.png?v=1619720111&auto=format,compress&w=900"),
                        new Item(41, "UZURI AFRICAN BLEND",
                                        "Help small-scale farmers improve their lives with every cup of this exquisite, juicy coffee.",
                                        21, "peets",
                                        "https://peets-shop.imgix.net/products/UAB-M_1.png?v=1592873765&auto=format,compress&w=900"),
                        new Item(42, "DECAF MAJOR DICKASON'S BLEND",
                                        "Quite possibly the most flavorful cup of decaf you’ll ever taste. Our most popular blend, without caffeine.",
                                        20, "peets",
                                        "https://peets-shop.imgix.net/products/DMA-M_1.png?v=1592870547&auto=format,compress&w=900"),
                        new Item(43, "ARABIAN MOCHA-JAVA",
                                        "Steeped in myth and origin, you can taste the full-bodied nature of the best mocha beans from East and West in this world-famous blend.",
                                        20, "peets",
                                        "https://peets-shop.imgix.net/products/MJV-M_1.png?v=1592867112&auto=format,compress&w=900"),
                        new Item(44, "GAIA ORGANIC BLEND",
                                        "Follow the cycle of the seasons with this bounteous world blend of certified organic coffees from Africa, Indonesia, and the Americas.",
                                        21, "peets",
                                        "https://peets-shop.imgix.net/products/GAI-M_1.png?v=1592871667&auto=format,compress&w=900"),
                        new Item(45, "KENYA AUCTION LOT",
                                        "Many say Kenyan coffee is the best there is; we don't think there's any better than our Auction Lot— juicy, complex, sweet, and dazzling.",
                                        21, "peets",
                                        "https://peets-shop.imgix.net/products/KEN-M_1.png?v=1592872641&auto=format,compress&w=900")));
}
