package com.coffee.server;

import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;

public class DummyData {
    public static List<Item> items = new ArrayList<>(Arrays.asList(
        new Item(1, "Stumptown Hair Bender",
                "The sweet and balanced coffee that started it all. Hair Bender is our most celebrated blend with a flavor profile that shines no matter how you brew it.",
                16,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/STCShopifyHairbender_ProductImageTransparentPNG_large.png?v=1622754826&auto=format,compress&w=540"),
        new Item(2, "Stumptown House Blend",
                "Our House Blend bag has officially been retired and replaced with Homestead! House Blend and Homestead are favs around here — in part because they’re so exceptionally similar — blended from many of the same components.",
                16,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/STCShopifyHouseBlend_ProductImageTransparentPNG.png?v=1622144063&auto=format,compress&w=750"),
        new Item(3, "Stumptown French Roast",
                "This toasty, organic blend redefines what a classic dark roast can be. It’s big and smoky, but never burnt.",
                17,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/STCShopifyFrenchRoast_ProductImageTransparentPNG_large.png?v=1622143647&auto=format,compress"),
        new Item(4, "Stumptown Roaster's Pick",
                "Like changing things up? Get a different coffee every two weeks—hand selected by the fine folks who source, cup, and roast our coffees—including some exclusive coffees only available through Roaster's Pick.",
                23,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/Roaster_sPickbadgeMordecofe_large.png?v=1679511247&auto=format,compress&w=540"),
        new Item(5, "Stumptown Blend Shuffle",
                "Keep it simple and fresh with a rotation of our iconic blends. We’ll send a new selection every two weeks, so you can say bye-bye to wasting away in the coffee aisle of your local grocery.",
                17,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/Blend_Shuffle_Holler_large.png?v=1679511223&auto=format,compress&w=540"),
        new Item(6, "Stumptown Holler Mountain",
                "This organic blend has been a hometown favorite since day one. It’s got the complexity to pour a great espresso yet the versatility to serve as your daily cup of drip.",
                17,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/STCShopifyHollerMountain_ProductImageTransparentPNG_large.png?v=1622754924&auto=format,compress&w=540"),
        new Item(7, "Stumptown Ecuador Rancho Carmen",
                "Stumptown sources this exquisite single origin offering from a group of 35 producers in Ecuador’s southernmost province.",
                23,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/SO_Bag_RanchoCarmen2023_1_large.png?v=1680551397&auto=format,compress&w=540"),
        new Item(8, "Stumptown Founder's Blend",
                "A smooth, all-day drinker, Founder's Blend combines certified organic coffees from Central and South America for a taste of sunshine in a cup.",
                17,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/Founders_Blend_Product_1_large.png?v=1649951363&auto=format,compress&w=540"),
        new Item(9, "Stumptown Trapper Creek Decaf",
                "Finally, decaf coffee beans that hold their own. Using the Swiss Water Process to decaffeinate carefully sourced coffees, we achieve unparalleled flavor and cup quality.",
                17,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/STCShopifyTrapperCreek_ProductImageTransparentPNG_large.png?v=1622755412&auto=format,compress&w=540"),
        new Item(10, "Stumptown Costa Rica Montes De Oro",
                "Montes de Oro is a farm and micro-mill managed by our longtime partners Emilio and Laura Gamboa in Tarrazú, Costa Rica. Their dedication to producing the finest coffee possible shines through in every cup.",
                23,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/STC-Shopify-Costa-Rica-Montes-De-Oro2021_Product-Image-Transparent-PNG_large.png?v=1637625830&auto=format,compress&w=540"),
        new Item(11, "Stumptown Rwanda Huye Mountain",
                "David Rubanzangabo operates the Huye Mountain washing station with an emphasis on community, and a strong dedication to the farmers it serves, resulting in a bright coffee with a fine, balanced acidity.",
                23,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/Rwanda_Huye_Mountain_2023_1_large.png?v=1673052779&auto=format,compress&w=540"),
        new Item(12, "Stumptown Peru Churupampa",
                "The Tocto family operates Finca Churupampa with an unwavering commitment to organic coffee production and their community.",
                23,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/STC-Shopify-PDP-Peru_Churupampa_1_large.png?v=1641783924&auto=format,compress&w=540"),
        new Item(13, "Stumptown Indonesia Bies Penantan",
                "This rich, full-bodied coffee is the result of carefully selected lots prepared and produced by our longtime partners at the women-led Ketiara Cooperative in Aceh, on the island of Sumatra.",
                21,
                "stumptown",
                "https://stumptown-shop.imgix.net/products/2022STC-Shopify-Indonesia-Bies_Product-Image-Transparent-PNG__2_large.png?v=1677883288&auto=format,compress&w=540")));

}

